import { SystemField } from './types';

// APF Dashboard is SFM-APF-1XXX-X
export const apfPageFields: SystemField[] = [
  // APF Dashboard Main Cards (SFM-APF-1001 to SFM-APF-1009)
  {
    sfmId: "SFM-APF-1001",
    description: "Annual Salary (Base Reference)",
    pageName: "APF Dashboard",
    cardName: "Main Cards",
    outputValue: "annualSalary",
    correlatedTo: "SFM-PRF-2021 - Profile Annual Salary",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1002",
    description: "Annual Salary with Inflation",
    pageName: "APF Dashboard",
    cardName: "Main Cards",
    outputValue: "annualSalaryWithInflation",
    correlatedTo: "SFM-PRF-2021 × (1 + SFM-CAL-4402)^SFM-CAL-4111 - Annual salary adjusted for inflation over time to retirement",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1003",
    description: "Paydays Remaining",
    pageName: "APF Dashboard",
    cardName: "Main Cards",
    outputValue: "paydaysRemaining",
    correlatedTo: "SFM-CAL-4113 - Paydays Remaining",
    valueType: "Time Period"
  },
  {
    sfmId: "SFM-APF-1004",
    description: "Target Income at Retirement",
    pageName: "APF Dashboard",
    cardName: "APF Summary Card",
    outputValue: "targetIncomeAtRetirement",
    correlatedTo: "SFM-CAL-4107 - Target Income at Retirement",
    valueType: "Retirement"
  },
  {
    sfmId: "SFM-APF-1005",
    description: "Projected Pension Income at Retirement",
    pageName: "APF Dashboard",
    cardName: "APF Summary Card",
    outputValue: "projectedPensionIncome",
    correlatedTo: "(SFM-CAL-4119 × SFM-CAL-4404) + SFM-CAL-4109 - (Total Projected Pension Value × Drawdown Rate) + State Pension at Retirement",
    valueType: "Retirement"
  },
  {
    sfmId: "SFM-APF-1006",
    description: "Income Shortfall at Retirement",
    pageName: "APF Dashboard",
    cardName: "APF Summary Card",
    outputValue: "incomeShortfall",
    correlatedTo: "SFM-CAL-4107 − SFM-APF-1005 - Target Income − Projected Income (ensure non-negative)",
    valueType: "Retirement"
  },
  {
    sfmId: "SFM-APF-1007",
    description: "Target Income at Retirement",
    pageName: "APF Dashboard",
    cardName: "APF Income Analysis",
    outputValue: "targetIncomeAtRetirement",
    correlatedTo: "SFM-PRF-2022 - Target income at retirement",
    valueType: "Retirement"
  },
  {
    sfmId: "SFM-APF-1008",
    description: "Projected Pension Income at Retirement",
    pageName: "APF Dashboard",
    cardName: "APF Income Analysis",
    outputValue: "projectedPensionIncome",
    correlatedTo: "SFM-PRF-2023 - Projected pension income at retirement",
    valueType: "Retirement"
  },
  {
    sfmId: "SFM-APF-1009",
    description: "Income Shortfall at Retirement",
    pageName: "APF Dashboard",
    cardName: "APF Income Analysis",
    outputValue: "incomeShortfall",
    correlatedTo: "(SFM-APF-1004 - SFM-APF-1005) - Income gap to be filled by APF",
    valueType: "Retirement"
  },

  // REMOVED DUPLICATE HARDCODED APF-11XX ENTRIES (lines 118-229)
  // These are now generated by generateAPFYearCodes() function

  // APF Registration Fields (SFM-APF-1200 to SFM-APF-1299)
  {
    sfmId: "SFM-APF-1201",
    description: "APF Registration - INBL Principal Amount",
    pageName: "APF Registration",
    cardName: "INBL Summary Card",
    outputValue: "inblPrincipalAmount",
    correlatedTo: "Replaces legacy SFM-144 - INBL principal funding amount",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1202",
    description: "APF Registration - INBL Interest/Growth",
    pageName: "APF Registration",
    cardName: "INBL Summary Card",
    outputValue: "inblInterestGrowth",
    correlatedTo: "Replaces legacy SFM-145 - INBL interest and growth amount",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1203",
    description: "APF Registration - INBL Total Value",
    pageName: "APF Registration",
    cardName: "INBL Summary Card",
    outputValue: "inblTotalValue",
    correlatedTo: "Replaces legacy SFM-146 - Total INBL value (principal + interest)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1204",
    description: "APF Registration - NRSR Annual Fee",
    pageName: "APF Registration",
    cardName: "NRSR Fee Card",
    outputValue: "nrsrAnnualFee",
    correlatedTo: "Replaces legacy SFM-155 - NRSR annual fee amount",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1205",
    description: "APF Registration - NRSR Monthly Fee",
    pageName: "APF Registration",
    cardName: "NRSR Fee Card",
    outputValue: "nrsrMonthlyFee",
    correlatedTo: "Replaces legacy SFM-156 - NRSR monthly fee amount",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1206",
    description: "APF Registration - NRSR Total Fee",
    pageName: "APF Registration",
    cardName: "NRSR Fee Card",
    outputValue: "nrsrTotalFee",
    correlatedTo: "Replaces legacy SFM-157 - Total NRSR fee amount",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1207",
    description: "APF Registration - INBL Year 1 Repayment",
    pageName: "APF Registration",
    cardName: "INBL Repayment Plan Card",
    outputValue: "inblYear1Repayment",
    correlatedTo: "Replaces legacy SFM-151 - INBL Year 1 repayment amount",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1208",
    description: "APF Registration - INBL Year 2 Repayment",
    pageName: "APF Registration",
    cardName: "INBL Repayment Plan Card",
    outputValue: "inblYear2Repayment",
    correlatedTo: "Replaces legacy SFM-152 - INBL Year 2 repayment amount",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1209",
    description: "APF Registration - INBL Year 3 Repayment",
    pageName: "APF Registration",
    cardName: "INBL Repayment Plan Card",
    outputValue: "inblYear3Repayment",
    correlatedTo: "Replaces legacy SFM-153 - INBL Year 3 repayment amount",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1210",
    description: "APF Registration - INBL Year 4 Repayment",
    pageName: "APF Registration",
    cardName: "INBL Repayment Plan Card",
    outputValue: "inblYear4Repayment",
    correlatedTo: "Replaces legacy SFM-154 - INBL Year 4 repayment amount",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1211",
    description: "APF Registration - ISA Monthly Savings",
    pageName: "APF Registration",
    cardName: "ISA Repayment Chart",
    outputValue: "isaMonthlyAmount",
    correlatedTo: "SFM-CAL-4261-M - ISA monthly savings for 252-month tranche (21 years), escalating after month 12, ceasing at month 251",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1212",
    description: "APF Registration - Sponsorship Years Count",
    pageName: "APF Registration",
    cardName: "Sponsorship Years Card",
    outputValue: "sponsorshipYearsCount",
    correlatedTo: "Replaces legacy SFM-150 - Number of sponsorship years",
    valueType: "Count"
  },

  // APF & INBL Summary - Total Program (SFM-APF-1281 to SFM-APF-1283)
  {
    sfmId: "SFM-APF-1281",
    description: "APF Registration - Total Initial Funding",
    pageName: "APF Registration",
    cardName: "APF & INBL Summary - Total Program",
    outputValue: "apfTotalInitialFunding",
    correlatedTo: "Sum of APF sponsorship contributions across all years",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1282",
    description: "APF Registration - Total Maturity Value",
    pageName: "APF Registration",
    cardName: "APF & INBL Summary - Total Program",
    outputValue: "apfTotalMaturityValue",
    correlatedTo: "Total APF maturity across all sponsorship years",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1283",
    description: "APF Registration - Total INBL Principal",
    pageName: "APF Registration",
    cardName: "APF & INBL Summary - Total Program",
    outputValue: "totalINBLPrincipal",
    correlatedTo: "Aggregate INBL principal balance funded by APF",
    valueType: "Currency"
  },

  // NEW SFM CODE MAPPINGS PROVIDED BY USER
  {
    sfmId: "SFM-APF-1010",
    description: "APF Registration - Net Pay Comparison",
    pageName: "APF Registration",
    cardName: "Net Pay Comparison Card",
    outputValue: "netPayComparison",
    correlatedTo: "Replaces legacy SFM-158 - Net pay comparison value",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1260",
    description: "APF Registration - AE Equivalent Year 1",
    pageName: "APF Registration",
    cardName: "AE Equivalent Card",
    outputValue: "aeEquivalentYear1",
    correlatedTo: "Replaces legacy SFM-060 - AE equivalent calculation year 1",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1261",
    description: "APF Registration - AE Equivalent Year 2",
    pageName: "APF Registration",
    cardName: "AE Equivalent Card",
    outputValue: "aeEquivalentYear2",
    correlatedTo: "Replaces legacy SFM-061 - AE equivalent calculation year 2",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1262",
    description: "APF Registration - AE Equivalent Year 3",
    pageName: "APF Registration",
    cardName: "AE Equivalent Card",
    outputValue: "aeEquivalentYear3",
    correlatedTo: "Replaces legacy SFM-062 - AE equivalent calculation year 3",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1263",
    description: "APF Registration - Value for Money Year 1",
    pageName: "APF Registration",
    cardName: "Value for Money Card",
    outputValue: "valueForMoneyYear1",
    correlatedTo: "Replaces legacy SFM-063 - Value for money calculation year 1",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1264",
    description: "APF Registration - Value for Money Year 2",
    pageName: "APF Registration",
    cardName: "Value for Money Card",
    outputValue: "valueForMoneyYear2",
    correlatedTo: "Replaces legacy SFM-064 - Value for money calculation year 2",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1265",
    description: "APF Registration - Value for Money Year 3",
    pageName: "APF Registration",
    cardName: "Value for Money Card",
    outputValue: "valueForMoneyYear3",
    correlatedTo: "Replaces legacy SFM-065 - Value for money calculation year 3",
    valueType: "Currency"
  },

  // Step 5: Salary Exchange & NPG (APF Registration)
  {
    sfmId: "SFM-APF-1501",
    description: "APF Registration - Existing Annual Salary",
    pageName: "APF Registration",
    cardName: "Salary Exchange Summary",
    outputValue: "annualSalary",
    correlatedTo: "SFM-PRF-2021 - Profile Annual Salary",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1502",
    description: "APF Registration - Existing Monthly Salary",
    pageName: "APF Registration",
    cardName: "Salary Exchange Summary",
    outputValue: "monthlySalary",
    correlatedTo: "SFM-PRF-2021 / 12",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1503",
    description: "APF Registration - Existing Annual Net Pay",
    pageName: "APF Registration",
    cardName: "Salary Exchange Summary",
    outputValue: "annualNetPayBefore",
    correlatedTo: "Annual net pay before APF changes",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1504",
    description: "APF Registration - Existing Monthly Net Pay",
    pageName: "APF Registration",
    cardName: "Salary Exchange Summary",
    outputValue: "monthlyNetPayBefore",
    correlatedTo: "Monthly net pay before APF changes",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1505",
    description: "APF Registration - Proposed Annual Salary",
    pageName: "APF Registration",
    cardName: "Salary Exchange Summary",
    outputValue: "proposedGrossAnnualSalary",
    correlatedTo: "Existing Annual Salary − Proposed Annual Salary Exchange",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1506",
    description: "APF Registration - Proposed Monthly Salary",
    pageName: "APF Registration",
    cardName: "Salary Exchange Summary",
    outputValue: "proposedGrossMonthlySalary",
    correlatedTo: "Existing Monthly Salary − Proposed Monthly Salary Exchange",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1507",
    description: "APF Registration - Proposed Annual Salary Exchange",
    pageName: "APF Registration",
    cardName: "Salary Exchange Summary",
    outputValue: "annualSalaryExchange",
    correlatedTo: "Annual salary sacrifice amount (feasible APF funding)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1508",
    description: "APF Registration - Proposed Monthly Salary Exchange",
    pageName: "APF Registration",
    cardName: "Salary Exchange Summary",
    outputValue: "monthlySalaryExchange",
    correlatedTo: "Monthly salary sacrifice amount (annual / 12)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1509",
    description: "APF Registration - Proposed Annual Net Pay",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Card",
    outputValue: "annualNetPayAfter",
    correlatedTo: "Annual net pay after APF including NPG",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1510",
    description: "APF Registration - Proposed Monthly Net Pay",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Card",
    outputValue: "monthlyNetPayAfter",
    correlatedTo: "Monthly net pay after APF including NPG",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1511",
    description: "APF Registration - Net Pay Reduction (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Card",
    outputValue: "annualNetPayReduction",
    correlatedTo: "Annual net pay reduction (Before − After)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1512",
    description: "APF Registration - Net Pay Guarantee (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Card",
    outputValue: "annualNetPayGuarantee",
    correlatedTo: "Annual Net Pay Guarantee (applied where reduction would exceed NPG)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1513",
    description: "APF Registration - Net Pay Reduction (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Card",
    outputValue: "monthlyNetPayReduction",
    correlatedTo: "Monthly net pay reduction (Before − After)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1514",
    description: "APF Registration - Net Pay Guarantee (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Card",
    outputValue: "monthlyNetPayGuarantee",
    correlatedTo: "Monthly Net Pay Guarantee (applied where reduction would exceed NPG)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1520",
    description: "APF Registration - Current Gross Pay (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentGrossPayMonthly",
    correlatedTo: "Monthly gross pay before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1521",
    description: "APF Registration - Current Pension Contribution (AE) (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentPensionContributionMonthly",
    correlatedTo: "Monthly AE pension contribution before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1522",
    description: "APF Registration - Current Gross Pay After Pension (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentGrossAfterPensionMonthly",
    correlatedTo: "Monthly gross pay after AE pension before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1523",
    description: "APF Registration - Current Income Tax (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentIncomeTaxMonthly",
    correlatedTo: "Monthly income tax before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1524",
    description: "APF Registration - Current National Insurance (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentNationalInsuranceMonthly",
    correlatedTo: "Monthly national insurance before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1525",
    description: "APF Registration - Current Net Pay (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentNetPayMonthly",
    correlatedTo: "Monthly net pay before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1530",
    description: "APF Registration - Total Salary Exchange (Schedule)",
    pageName: "APF Registration",
    cardName: "Monthly Salary Exchange Schedule",
    outputValue: "totalSalaryExchange",
    correlatedTo: "Total salary exchange across schedule months",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1531",
    description: "APF Registration - Total Net Pay Reduction (Schedule)",
    pageName: "APF Registration",
    cardName: "Monthly Salary Exchange Schedule",
    outputValue: "totalNetPayReduction",
    correlatedTo: "Total net pay reduction across schedule months",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1532",
    description: "APF Registration - Total Net Pay Guarantee (Schedule)",
    pageName: "APF Registration",
    cardName: "Monthly Salary Exchange Schedule",
    outputValue: "totalNetPayGuarantee",
    correlatedTo: "Total Net Pay Guarantee across schedule months",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1533",
    description: "APF Registration - New Gross Pay (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "newGrossPayMonthly",
    correlatedTo: "Monthly gross pay after APF (pre-sacrifice base)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1534",
    description: "APF Registration - APF Salary Sacrifice (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "apfSalarySacrificeMonthly",
    correlatedTo: "Monthly salary exchange applied",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1535",
    description: "APF Registration - Gross Pay After APF (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "grossPayAfterAPFMonthly",
    correlatedTo: "Monthly gross pay after APF (post-sacrifice)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1536",
    description: "APF Registration - Income Tax After APF (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "incomeTaxAfterMonthly",
    correlatedTo: "Monthly income tax after APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1537",
    description: "APF Registration - National Insurance After APF (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "nationalInsuranceAfterMonthly",
    correlatedTo: "Monthly national insurance after APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1538",
    description: "APF Registration - INBL Loan Support (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "inblLoanSupportMonthly",
    correlatedTo: "Monthly INBL loan support applied",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1539",
    description: "APF Registration - New Net Pay (Monthly)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "newNetPayMonthly",
    correlatedTo: "Monthly net pay after APF (including INBL)",
    valueType: "Currency"
  },

  // Payslip Comparison Popup (Annual equivalents)
  {
    sfmId: "SFM-APF-1540",
    description: "APF Registration - Current Gross Pay (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentGrossPayAnnual",
    correlatedTo: "Annual gross pay before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1541",
    description: "APF Registration - Current Pension Contribution (AE) (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentPensionContributionAnnual",
    correlatedTo: "Annual AE pension contribution before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1542",
    description: "APF Registration - Current Gross Pay After Pension (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentGrossAfterPensionAnnual",
    correlatedTo: "Annual gross pay after AE pension before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1543",
    description: "APF Registration - Current Income Tax (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentIncomeTaxAnnual",
    correlatedTo: "Annual income tax before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1544",
    description: "APF Registration - Current National Insurance (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentNationalInsuranceAnnual",
    correlatedTo: "Annual national insurance before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1545",
    description: "APF Registration - Current Net Pay (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "currentNetPayAnnual",
    correlatedTo: "Annual net pay before APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1550",
    description: "APF Registration - New Gross Pay (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "newGrossPayAnnual",
    correlatedTo: "Annual gross pay after APF (pre-sacrifice base)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1551",
    description: "APF Registration - APF Salary Sacrifice (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "apfSalarySacrificeAnnual",
    correlatedTo: "Annual salary exchange applied",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1552",
    description: "APF Registration - Gross Pay After APF (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "grossPayAfterAPFAnnual",
    correlatedTo: "Annual gross pay after APF (post-sacrifice)",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1553",
    description: "APF Registration - Income Tax After APF (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "incomeTaxAfterAnnual",
    correlatedTo: "Annual income tax after APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1554",
    description: "APF Registration - National Insurance After APF (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "nationalInsuranceAfterAnnual",
    correlatedTo: "Annual national insurance after APF",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1555",
    description: "APF Registration - INBL Loan Support (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "inblLoanSupportAnnual",
    correlatedTo: "Annual INBL loan support applied",
    valueType: "Currency"
  },
  {
    sfmId: "SFM-APF-1556",
    description: "APF Registration - New Net Pay (Annual)",
    pageName: "APF Registration",
    cardName: "Payslip Comparison Popup",
    outputValue: "newNetPayAnnual",
    correlatedTo: "Annual net pay after APF (including INBL)",
    valueType: "Currency"
  },

  // APF Plan Overview Fields (SFM-APF-1300 to SFM-APF-1399)
  {
    sfmId: "SFM-APF-1301",
    description: "APF Plan Summary",
    pageName: "APF Plan Overview",
    cardName: "Plan Summary",
    outputValue: "apfPlanSummary",
    correlatedTo: "Complete APF plan overview",
    valueType: "Summary"
  },
  {
    sfmId: "SFM-APF-1302",
    description: "APF Total Investment Required",
    pageName: "APF Plan Overview",
    cardName: "Investment Requirements",
    outputValue: "apfTotalInvestment",
    correlatedTo: "Total APF investment required over all years",
    valueType: "Total Amount"
  },
  {
    sfmId: "SFM-APF-1303",
    description: "APF Expected Return",
    pageName: "APF Plan Overview",
    cardName: "Return Projections",
    outputValue: "apfExpectedReturn",
    correlatedTo: "Expected APF return at retirement",
    valueType: "Retirement"
  }
];

// Generate all year-specific codes (1-9 + F) for each APF metric
export const generateAPFYearCodes = (): SystemField[] => {
  const yearCodes: SystemField[] = [];
  const years = ['1', '2', '3', '4', '5', '6', '7', '8', '9', 'F'];
  const metrics = ['C', 'V', 'G']; // Contribution, Value, Growth
  
  years.forEach(year => {
    const baseCode = year === 'F' ? 1110 : 1100 + parseInt(year);
    
    // Sponsorship amount for each year
    yearCodes.push({
      sfmId: `SFM-APF-${baseCode}-${year}`,
      description: `APF Year ${year === 'F' ? 'Final' : year} Sponsorship Amount`,
      pageName: "APF Dashboard",
      cardName: "Sponsorship Breakdown",
      outputValue: `apfYear${year === 'F' ? 'Final' : year}Amount`,
      correlatedTo: `Year ${year === 'F' ? 'Final' : year} APF sponsorship funding amount`,
      valueType: `Year ${year === 'F' ? 'Final' : year} Amount`
    });
    
    // C, V, G metrics for each year (UPDATED: Removed "Contributions Paid" from description)
    metrics.forEach(metric => {
      const metricName = metric === 'C' ? 'Contributions' : metric === 'V' ? 'Value' : 'Growth';
      yearCodes.push({
        sfmId: `SFM-APF-${baseCode}-${metric}`,
        description: `APF Year ${year === 'F' ? 'Final' : year} ${metricName}`,
        pageName: "APF Dashboard",
        cardName: "Sponsorship Breakdown",
        outputValue: `apfYear${year === 'F' ? 'Final' : year}${metricName}`,
        correlatedTo: `${metricName} for year ${year === 'F' ? 'final' : year} sponsorship`,
        valueType: metricName
      });
    });
  });
  
  return yearCodes;
};