// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybronliyhpjprquyzsac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlicm9ubGl5aHBqcHJxdXl6c2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzQ0MjAsImV4cCI6MjA2MjkxMDQyMH0.luC3m_3IvNufyZed2nDtAEYNKoV2GQofmlEUJgtemBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);